name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Setup
      run: make setup
    - name: Lint
      run: make lint
    - name: Freeze flask
      run: make freeze
    - name: Push static page
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --global user.email "www.kentaro.wada@gmail.com"
        git config --global user.name "Kentaro Wada"
        git add wkentaro_com/build
        git diff-index --cached --quiet HEAD || git commit -m "Update wkentaro_com/build"
        git push origin main
        git subtree split --prefix wkentaro_com/build -b gh-pages
        git push -f origin gh-pages:gh-pages
        git branch -D gh-pages
